
version: "3"

services:
  airo-db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  metabase-db:
    image: postgres
    expose:
      - "5432"
    volumes:
      - ./metabase/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=password
  analysis:
    image: metabase/metabase
    ports:
      - "12345:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=postgres
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=password
      - MB_DB_HOST=metabase-db
    depends_on:
      - metabase-db
    links:
      - metabase-db
